### ISSUE TITLE
希望可以增加推送

### ISSUE THREAD

**Issue by heyzg** [0wQ/air724ug-forwarder#1]
https://push.luatos.org/
合宙官方的推送
另外这个Air724ug可以连接WiFi吗？
如果可以的话希望大佬怎加一个连接WiFi的功能

**Comment by 0wQ** [comment]
Air724UG 请求这个网站貌似会报错，已经发 [issue](https://gitee.com/openLuat/Luat_Lua_Air724U/issues/I64I1Z?from=project-issue) 了

不可以连接 wifi，只能扫描 wifi

**Comment by 0wQ** [comment]
合宙貌似不会解决了，而且用这个发通知会有长度限制，太长的会请求失败。

可以等过一段时间，我会把 [air780e-forwarder](https://github.com/0wQ/air780e-forwarder) 这个项目支持的的通知渠道加进来，合宙官方推送支持的基本都有了

**Comment by 0wQ** [comment]
已添加
