### ISSUE TITLE
请问录音上传是默认开启的吗

### ISSUE THREAD

**Issue by lihtao** [0wQ/air724ug-forwarder#10]
如果我需要关闭这个功能，尽量不要让使用流量，请问在哪里配置

**Comment by lihtao** [comment]
https://github.com/0wQ/air724ug-forwarder/blob/main/script/config.lua#:~:text=%2D%2D%20%E5%AE%9A%E6%97%B6%E4%B8%8A,60%20*%2030%2C
这里可以👌

**Comment by 0wQ** [comment]
> https://github.com/0wQ/air724ug-forwarder/blob/main/script/config.lua#:~:text=%2D%2D%20%E5%AE%9A%E6%97%B6%E4%B8%8A,60%20*%2030%2C 这里可以👌

这个不是，新写的版本可以，有扬声器功能，按键可以控制各配置的开关，可以配置来电自动接听、拒接、挂断，有时间我更新一下😂

**Comment by lihtao** [comment]
> > https://github.com/0wQ/air724ug-forwarder/blob/main/script/config.lua#:~:text=%2D%2D%20%E5%AE%9A%E6%97%B6%E4%B8%8A,60%20*%2030%2C 这里可以👌
> 
> 这个不是，新写的版本可以，有扬声器功能，按键可以控制各配置的开关，可以配置来电自动接听、拒接、挂断，有时间我更新一下😂

那在哪里配置可以不让它发起录音上传的request，我主要是没有流量🤣

**Comment by 0wQ** [comment]
> > > https://github.com/0wQ/air724ug-forwarder/blob/main/script/config.lua#:~:text=%2D%2D%20%E5%AE%9A%E6%97%B6%E4%B8%8A,60%20*%2030%2C 这里可以👌
> > 
> > 
> > 这个不是，新写的版本可以，有扬声器功能，按键可以控制各配置的开关，可以配置来电自动接听、拒接、挂断，有时间我更新一下😂
> 
> 那在哪里配置可以不让它发起录音上传的request，我主要是没有流量🤣

试试把这里删掉
https://github.com/0wQ/air724ug-forwarder/blob/ae7e6f511c4dcfea9a33e42c0a179bae2a1a4d34/script/handler_call.lua#L230-L233

**Comment by lihtao** [comment]
👌感谢大佬
