### ISSUE TITLE
同种配置支持多个?

### ISSUE THREAD

**Issue by huoshenlaile** [0wQ/air724ug-forwarder#11]
如题, 我正在用bark作为推送方式, 配置文件里如何实现多个bark推送? 十分感谢

**Comment by 0wQ** [comment]
目前还不支持设置多个相同的，设置第二个 bark 可以使用 [Inotify](https://github.com/xpnas/Inotify) 或者合宙提供的 https://push.luatos.org/

**Comment by huoshenlaile** [comment]
好吧我自己改了一个版本支持多个bark了, 但魔改的东西挺多, 还加上了uptime自动检测, 但把有的功能去掉了...
