### ISSUE TITLE
请求增加对繁体字的支持

### ISSUE THREAD

**Issue by obpsf** [0wQ/air724ug-forwarder#15]
收到繁体字的短信，转发后无法显示繁体的字，如下：

【中　　信提示】682675(　　　，　勿　露）此　　　5分　　有效！如非本人操作，　忽略本短　。

**Comment by 0wQ** [comment]
试一下现在解决了吗？

**Comment by obpsf** [comment]
> 试一下现在解决了吗？

解决了！十分感谢！
