### ISSUE TITLE
作者您好，想咨询一下卡死的情况

### ISSUE THREAD

**Issue by github410117** [0wQ/air724ug-forwarder#22]
根据教程以及固件进行了刷机，功能正常使用，但是会在3-5天就会卡死，就是无法转发短信，重新上电就可以，但是由于是直接用充电头供电的，没有一直插在电脑上，能有办法看到卡死的日志吗？

**Comment by wchfcool** [comment]
我使用了大概三个多月，也有这个问题，具体日志为
[2023-12-09 19:06:04.477] [I]-[ril.proatc] +CIEV: "MESSAGE",1
[2023-12-09 19:06:04.477] [I]-[ril.defurc] +CIEV: "MESSAGE",1
[2023-12-09 19:06:04.477] 
[2023-12-09 19:06:04.477] +CIEV: "MESSAGE",1
没有后续动作，正常情况会继续读取短信内容执行操作，可是这个日志，感觉是设备知道有短信进来，但是读取短信的线程抛出了
如果能够解决，真是万分感谢，目前本项目代码真是完善，唯独这个造成掉线

不知道是代码原因还是底层系统就有这个bug。不知道这里能否加个判断，出现情况就重启。

而且这种没有读取的短信，又好像从运营商拉下来了，因为设备重启后，并没有这条短信进来，造成丢失

**Comment by lfmwuy** [comment]
你试试最新的底层看看
V4026底层固件更新说明
1：可选编译支持ipv6功能:
2：增加对795的自适应
3：解决移动卡在特定情况下对6F7E写入问题:
4：解决通过audiocore.streamplay播放音频数据，但监听不到语音流结束的问题
5：更新sm2库相关联的文件

**Comment by 0wQ** [comment]
> 我使用了大概三个多月，也有这个问题，具体日志为 [2023-12-09 19:06:04.477] [I]-[ril.proatc] +CIEV: "MESSAGE",1 [2023-12-09 19:06:04.477] [I]-[ril.defurc] +CIEV: "MESSAGE",1 [2023-12-09 19:06:04.477] [2023-12-09 19:06:04.477] +CIEV: "MESSAGE",1 没有后续动作，正常情况会继续读取短信内容执行操作，可是这个日志，感觉是设备知道有短信进来，但是读取短信的线程抛出了 如果能够解决，真是万分感谢，目前本项目代码真是完善，唯独这个造成掉线
> 
> 不知道是代码原因还是底层系统就有这个bug。不知道这里能否加个判断，出现情况就重启。
> 
> 而且这种没有读取的短信，又好像从运营商拉下来了，因为设备重启后，并没有这条短信进来，造成丢失

我连续开机1个月了，一直没能遇到这个现象。怀疑有可能是我上个月的代码中已经修复了一些通话导致的bug，你可以尝试更新到最新的代码以及最新的官方底层固件。如果还有出现我考虑一下加个定时重启

**Comment by wchfcool** [comment]
这个问题并不经常出现，是小概率事件，所以可能您这没有出现，我的设备多，基本一两天就会发现一次，更新了最新底层和脚本，问题依然存在。目前解决办法是远程断电重启来解决的。
猜想可能官方存在这个bug，最新的lib文件跟你脚本带的有一些变化，我尝试过覆盖更新，但是短信出现乱码，所以也就没机会长期测试。

**Comment by 0wQ** [comment]
> 这个问题并不经常出现，是小概率事件，所以可能您这没有出现，我的设备多，基本一两天就会发现一次，更新了最新底层和脚本，问题依然存在。目前解决办法是远程断电重启来解决的。 猜想可能官方存在这个bug，最新的lib文件跟你脚本带的有一些变化，我尝试过覆盖更新，但是短信出现乱码，所以也就没机会长期测试。

目前发现收到彩信后再收普通短信可以复现该现象，你的卡会经常收到彩信吗？（建了个群有需要可以加一下756740965）

**Comment by wchfcool** [comment]
> > 这个问题并不经常出现，是小概率事件，所以可能您这没有出现，我的设备多，基本一两天就会发现一次，更新了最新底层和脚本，问题依然存在。目前解决办法是远程断电重启来解决的。 猜想可能官方存在这个bug，最新的lib文件跟你脚本带的有一些变化，我尝试过覆盖更新，但是短信出现乱码，所以也就没机会长期测试。
> 
> 目前发现收到彩信后再收普通短信可以复现该现象，你的卡会经常收到彩信吗？（建了个群有需要可以加一下756740965）

感谢作者，经过测试，最新代码已经修复短信满和卡彩信掉线的情况。
