### ISSUE TITLE
请问导入脚本，提示文件总数量超过了固件脚本区空间

### ISSUE THREAD

**Issue by lihtao** [0wQ/air724ug-forwarder#23]
![image](https://github.com/0wQ/air724ug-forwarder/assets/46276763/852807da-8775-4fab-a8b4-874d79d5ea34)
之前导入都是合适的，脚本基本上也没怎么改，是不是我导入的不对？

**Comment by 0wQ** [comment]
你看一下是不是底层CORE选错了，我看截图上是780的
