### ISSUE TITLE
新的问题

### ISSUE THREAD

**Issue by zyt0813** [0wQ/air724ug-forwarder#24]
有些功能设备需要与您探讨沟通一下 希望得到您的回复 谢谢

**Comment by 0wQ** [comment]
什么问题

**Comment by zyt0813** [comment]
方便换个联系方式 语音沟通吗

**Comment by zyt0813** [comment]
一般情况下都是通过网络流量，把短信的文本，通过互联网上传到服务器上，系统代码是可以修改的，就收到短信，把短信转发给另一个手机号

**Comment by zyt0813** [comment]
我可以有偿咨询老师

**Comment by zyt0813** [comment]
关于全球短信发送





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Mizore ***@***.***&gt;
发送时间: 2023年12月17日 14:25
收件人: 0wQ/air724ug-forwarder ***@***.***&gt;
抄送: zyt0813 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [0wQ/air724ug-forwarder] 新的问题 (Issue #24)





 
什么问题
