### ISSUE TITLE
请教一下录音上传的方式是否支持webdav方式？还有就是录音功能能否关闭？

### ISSUE THREAD

**Issue by cheng2004237** [0wQ/air724ug-forwarder#26]
请教一下录音上传的方式是否支持webdav方式？还有就是录音功能能否关闭？
如果支持，改修改代码的那一部分呢？因为webdav，需要用户名和密码验证。
谢谢啦～

**Comment by 0wQ** [comment]
webdav 自己实现可以参考 https://github.com/0wQ/air724ug-forwarder/issues/19

现在已经支持关闭录音上传了
