### ISSUE TITLE
电信卡，第二天开始就收不到短信

### ISSUE THREAD

**Issue by HiRules** [0wQ/air724ug-forwarder#32]
刷了几次了依旧如此，用的是最新固件和脚本，开发板带两个卡槽的那种，板子上只放了一张电信卡

![剪贴板](https://github.com/user-attachments/assets/163e70c4-4a5e-48ca-a568-de7b9c0f5357)

**Comment by 0wQ** [comment]
是收不到短信，还是收到短信了请求发送失败

可以将 2 改为 0.5 试一下
https://github.com/0wQ/air724ug-forwarder/blob/a6f3197f4eec634c4630a3da1646bf35aad991e7/script/utils/util_ntp.lua#L15

```lua
ntp.timeSync(0.5, function(time, result)
```

**Comment by HiRules** [comment]
> 是收不到短信，还是收到短信了请求发送失败
> 
> 可以将 2 改为 0.5 试一下
> 
> https://github.com/0wQ/air724ug-forwarder/blob/a6f3197f4eec634c4630a3da1646bf35aad991e7/script/utils/util_ntp.lua#L15
> 
> ```lua
> ntp.timeSync(0.5, function(time, result)
> ```

修改2-->0.5后，目前已经两天了，短信接收都正常。很好奇，这个参数负责什么功能，竟然这么管用！

**Comment by 0wQ** [comment]
> > 是收不到短信，还是收到短信了请求发送失败
> > 可以将 2 改为 0.5 试一下
> > https://github.com/0wQ/air724ug-forwarder/blob/a6f3197f4eec634c4630a3da1646bf35aad991e7/script/utils/util_ntp.lua#L15
> > 
> > ```lua
> > ntp.timeSync(0.5, function(time, result)
> > ```
> 
> 修改2-->0.5后，目前已经两天了，短信接收都正常。很好奇，这个参数负责什么功能，竟然这么管用！

有些地区的基站貌似一段时间没有流量请求，就会被踢下线，会有收到短信但发不出去的情况。
修改 ntp 同步时间间隔 2小时 -> 30 分钟，保持有请求，应该可以解决，也可以再改大一点试试。

**Comment by HiRules** [comment]
> > > 是收不到短信，还是收到短信了请求发送失败
> > > 可以将 2 改为 0.5 试一下
> > > https://github.com/0wQ/air724ug-forwarder/blob/a6f3197f4eec634c4630a3da1646bf35aad991e7/script/utils/util_ntp.lua#L15
> > > 
> > > ```lua
> > > ntp.timeSync(0.5, function(time, result)
> > > ```
> > 
> > 
> > 修改2-->0.5后，目前已经两天了，短信接收都正常。很好奇，这个参数负责什么功能，竟然这么管用！
> 
> 有些地区的基站貌似一段时间没有流量请求，就会被踢下线，会有收到短信但发不出去的情况。 修改 ntp 同步时间间隔 2小时 -> 30 分钟，保持有请求，应该可以解决，也可以再改大一点试试。

原来如此。那我再稍微改大一点点，不过这个同步的是时间吧，按理说消耗的流量比较小。
辛苦大佬了，结贴！
