### ISSUE TITLE
短信回调不起作用

### ISSUE THREAD

**Issue by im-zhou** [0wQ/air724ug-forwarder#33]
请问大佬，我自己写入了一个最简单的短信回调，作用仅仅是打印到log
为什么接到短信时没输出呢?
![d360adca-3acf-4eb6-8939-736dcfe58708](https://github.com/user-attachments/assets/787edd04-f3be-47e9-a95a-2411f1d1ff63)

**Comment by 0wQ** [comment]
用这个项目的代码是正常的吗，看着好像没什么问题

**Comment by im-zhou** [comment]
> 用这个项目的代码是正常的吗，看着好像没什么问题

就是用本项目不行，然后搞了这个最简单的代码写入，依旧是不行，难搞

**Comment by 0wQ** [comment]
> > 用这个项目的代码是正常的吗，看着好像没什么问题
> 
> 就是用本项目不行，然后搞了这个最简单的代码写入，依旧是不行，难搞

检查一下手机卡 volte 开启了吗

**Comment by im-zhou** [comment]
> > > 用这个项目的代码是正常的吗，看着好像没什么问题
> > 
> > 
> > 就是用本项目不行，然后搞了这个最简单的代码写入，依旧是不行，难搞
> 
> 检查一下手机卡 volte 开启了吗

VoLTE当然开启了，截图里面圈红的地方，就是已经收到短信了，就是不知道为什么回调没执行

**Comment by 0wQ** [comment]
> > 用这个项目的代码是正常的吗，看着好像没什么问题
> 
> 就是用本项目不行，然后搞了这个最简单的代码写入，依旧是不行，难搞

可以试一下合宙官方demo，固件也全部使用官方的，如果还是不行可以在该仓库提交issues

https://gitee.com/openLuat/Luat_Lua_Air724U/tree/master/script_LuaTask/demo/sms

**Comment by im-zhou** [comment]
🆗
