### ISSUE TITLE
求：加个wifi模块连接wifi使用

### ISSUE THREAD

**Issue by 520-GitHub** [0wQ/air724ug-forwarder#8]
求：加个wifi模块连接wifi使用

**Comment by 0wQ** [comment]
可以试试这个给780e用的，都是at指令，应该兼容724，https://www.chenxublog.com/2022/10/28/19-9-sms-forwarding-air780e-esp32c3.html

**Comment by kukudemajia** [comment]
> 可以试试这个给780e用的，都是at指令，应该兼容724，https://www.chenxublog.com/2022/10/28/19-9-sms-forwarding-air780e-esp32c3.html
功能略显简单，要是能把咱家的脚本适配到esp32_c3就好了
